import jsPDF from "jspdf";

export interface ConsentFormParams {
  orgName: string;
  participantName: string;
  ndisNumber: string;
  dob: string;
  propertyAddress: string;
}

/**
 * Generate a 2-page Consent to Collect, Use and Share Personal Information PDF.
 * Page 1: Consent form with clauses, signature blocks.
 * Page 2: Privacy Information Sheet (Your Privacy Rights).
 * Complies with Australian Privacy Principle 3 (APP 3).
 */
export function generateConsentFormPdf(params: ConsentFormParams): void {
  const { orgName, participantName, ndisNumber, dob, propertyAddress } = params;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  // ── PAGE 1: CONSENT FORM ──────────────────────────────────

  // Header bar
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 36, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(orgName, margin, 14);
  doc.text("ABN: [pending]", margin, 20);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Consent to Collect, Use and Share Personal Information", margin, 30);

  // Participant details section
  let y = 46;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Participant Details", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const detailRows = [
    { label: "Full Name:", value: participantName },
    { label: "NDIS Number:", value: ndisNumber },
    { label: "Date of Birth:", value: dob },
    { label: "Property Address:", value: propertyAddress },
  ];

  for (const row of detailRows) {
    doc.setFont("helvetica", "bold");
    doc.text(row.label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(row.value || "N/A", margin + 40, y);
    y += 6;
  }

  // Divider
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Consent clauses
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Consent Clauses", margin, y);
  y += 8;

  const clauses = [
    "I consent to the collection of my personal and health information for the purpose of managing my SDA tenancy.",
    "I understand my information may be shared with NDIS, SIL providers, and support coordinators as necessary.",
    "I have been informed of my right to access, correct, or request deletion of my personal information.",
    "I understand this consent is valid for 12 months from the date signed and can be withdrawn at any time.",
    "I have read the Privacy Information Sheet (overleaf) and understand how my information will be handled.",
  ];

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");

  for (let i = 0; i < clauses.length; i++) {
    // Checkbox graphic
    const checkboxX = margin;
    const checkboxY = y - 3;
    doc.setDrawColor(80, 80, 80);
    doc.setLineWidth(0.5);
    doc.rect(checkboxX, checkboxY, 4, 4);

    // Clause text with word wrap
    const lines = doc.splitTextToSize(
      `${i + 1}. ${clauses[i]}`,
      contentWidth - 8
    );
    doc.text(lines, margin + 7, y);
    y += lines.length * 5 + 4;
  }

  // Divider before signatures
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Signature block
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Declaration & Signatures", margin, y);
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    "By signing below, I confirm that I have read and understood the above clauses and the Privacy Information Sheet.",
    margin,
    y
  );
  y += 12;

  // Participant signature line
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.4);
  doc.line(margin, y + 8, margin + 80, y + 8);
  doc.setFontSize(8);
  doc.text("Participant / Authorised Representative Signature", margin, y + 13);

  // Date line
  doc.line(margin + 100, y + 8, margin + 150, y + 8);
  doc.text("Date", margin + 100, y + 13);

  y += 24;

  // Witness signature line
  doc.setLineWidth(0.4);
  doc.line(margin, y + 8, margin + 80, y + 8);
  doc.setFontSize(8);
  doc.text("Witness Name & Signature", margin, y + 13);

  // Witness date
  doc.line(margin + 100, y + 8, margin + 150, y + 8);
  doc.text("Date", margin + 100, y + 13);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Complies with Australian Privacy Principle 3 (APP 3) - Collection of solicited personal information",
    margin,
    footerY
  );
  doc.text(
    `Generated by MySDAManager on ${new Date().toLocaleDateString("en-AU")}`,
    margin,
    footerY + 4
  );
  doc.text("Page 1 of 2", pageWidth - margin - 20, footerY + 4);

  // ── PAGE 2: PRIVACY INFORMATION SHEET ──────────────────────
  doc.addPage();

  // Header bar
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Privacy Information Sheet", margin, 20);

  y = 40;
  doc.setTextColor(0, 0, 0);

  // Section helper
  const addSection = (title: string, content: string) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(content, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 6;
  };

  addSection(
    "Your Privacy Rights",
    "Under the Australian Privacy Act 1988 and the NDIS Act 2013, you have the right to know what personal " +
      "information we collect, why we collect it, who we share it with, and how you can access or correct your information. " +
      "This sheet explains these rights in plain language."
  );

  addSection(
    "What We Collect and Why",
    "We collect your personal information (name, contact details, NDIS number, date of birth) and health information " +
      "(SDA needs, disability support requirements) to:\n" +
      "- Manage your SDA tenancy and accommodation agreement\n" +
      "- Process SDA funding claims with the NDIS\n" +
      "- Coordinate with your SIL provider and support coordinator\n" +
      "- Meet our regulatory and reporting obligations\n" +
      "- Ensure the safety and suitability of your accommodation"
  );

  addSection(
    "Who We Share Your Information With",
    "We may share your information with:\n" +
      "- The National Disability Insurance Agency (NDIA) for funding and compliance purposes\n" +
      "- Your nominated SIL provider for daily support coordination\n" +
      "- Your Support Coordinator or Plan Manager as required\n" +
      "- Occupational Therapists conducting SDA assessments\n" +
      "- Emergency services when required for your safety\n" +
      "- Government bodies where legally required\n\n" +
      "We will never sell your personal information or share it for marketing purposes."
  );

  addSection(
    "How We Store Your Information",
    "Your information is stored securely in our digital management system with encryption at rest. " +
      "Access is restricted to authorised staff only. We retain your information for 7 years after your " +
      "tenancy ends, as required by NDIS record-keeping obligations."
  );

  addSection(
    "How to Withdraw Consent",
    "You can withdraw your consent at any time by contacting your property manager or SDA provider in writing. " +
      "If you withdraw consent:\n" +
      "- We will stop collecting new personal information\n" +
      "- Your NDIS number, date of birth, and emergency contacts will be archived\n" +
      "- Records required for legal or compliance purposes will be retained\n" +
      "- This may affect our ability to manage your SDA tenancy and process NDIS claims"
  );

  addSection(
    "How to Access or Correct Your Information",
    "You have the right to request access to your personal information at any time. " +
      "If you believe any information is incorrect, you can request a correction. " +
      "Contact your SDA provider directly to make a request."
  );

  addSection(
    "Making a Complaint",
    "If you believe your privacy has been breached, you can:\n" +
      "1. Contact us directly to lodge a complaint\n" +
      "2. Contact the NDIS Quality and Safeguards Commission: 1800 035 544\n" +
      "3. Contact the Office of the Australian Information Commissioner (OAIC):\n" +
      "   Phone: 1300 363 992 | Website: www.oaic.gov.au"
  );

  // Footer
  const footer2Y = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `${orgName} | Generated by MySDAManager on ${new Date().toLocaleDateString("en-AU")}`,
    margin,
    footer2Y
  );
  doc.text("Page 2 of 2", pageWidth - margin - 20, footer2Y);

  // Trigger download
  const safeName = participantName.replace(/[^a-zA-Z0-9]/g, "_");
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`Consent_Form_${safeName}_${dateStr}.pdf`);
}
