import jsPDF from "jspdf";

export interface ConsentFormParams {
  orgName: string;
  orgAbn?: string;
  participantName: string;
  ndisNumber: string;
  dob: string;
  propertyAddress: string;
}

/**
 * Generate a 2-page Consent to Collect, Use and Share Personal Information PDF.
 * Page 1: Consent form with clauses, signature blocks.
 * Page 2: Privacy Information Sheet (Your Privacy Rights).
 * Complies with Australian Privacy Principle 3 (APP 3).
 */
export function generateConsentFormPdf(params: ConsentFormParams): void {
  const { orgName, orgAbn, participantName, ndisNumber, dob, propertyAddress } = params;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  // ── PAGE 1: CONSENT FORM ──────────────────────────────────

  // Header bar
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 36, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(orgName, margin, 14);
  doc.text(orgAbn ? `ABN: ${orgAbn}` : "", margin, 20);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Consent to Collect, Use and Share Personal Information", margin, 30);

  // Participant details section
  let y = 46;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Participant Details", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const detailRows = [
    { label: "Full Name:", value: participantName },
    { label: "NDIS Number:", value: ndisNumber },
    { label: "Date of Birth:", value: dob },
    { label: "Property Address:", value: propertyAddress },
  ];

  for (const row of detailRows) {
    doc.setFont("helvetica", "bold");
    doc.text(row.label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(row.value || "N/A", margin + 40, y);
    y += 6;
  }

  // Divider
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Consent clauses
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Consent Clauses", margin, y);
  y += 8;

  const clauses = [
    "I consent to the collection of my personal and health information for the purpose of managing my SDA tenancy.",
    "I understand my information may be shared with NDIS, SIL providers, and support coordinators as necessary.",
    "I have been informed of my right to access, correct, or request deletion of my personal information.",
    "I understand this consent is valid for 12 months from the date signed and can be withdrawn at any time.",
    "I have read the Privacy Information Sheet (overleaf) and understand how my information will be handled.",
  ];

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");

  for (let i = 0; i < clauses.length; i++) {
    // Checkbox graphic
    const checkboxX = margin;
    const checkboxY = y - 3;
    doc.setDrawColor(80, 80, 80);
    doc.setLineWidth(0.5);
    doc.rect(checkboxX, checkboxY, 4, 4);

    // Clause text with word wrap
    const lines = doc.splitTextToSize(
      `${i + 1}. ${clauses[i]}`,
      contentWidth - 8
    );
    doc.text(lines, margin + 7, y);
    y += lines.length * 5 + 4;
  }

  // Divider before signatures
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Signature block
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Declaration & Signatures", margin, y);
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    "By signing below, I confirm that I have read and understood the above clauses and the Privacy Information Sheet.",
    margin,
    y
  );
  y += 12;

  // Participant signature line
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.4);
  doc.line(margin, y + 8, margin + 80, y + 8);
  doc.setFontSize(8);
  doc.text("Participant / Authorised Representative Signature", margin, y + 13);

  // Date line
  doc.line(margin + 100, y + 8, margin + 150, y + 8);
  doc.text("Date", margin + 100, y + 13);

  y += 24;

  // Witness signature line
  doc.setLineWidth(0.4);
  doc.line(margin, y + 8, margin + 80, y + 8);
  doc.setFontSize(8);
  doc.text("Witness Name & Signature", margin, y + 13);

  // Witness date
  doc.line(margin + 100, y + 8, margin + 150, y + 8);
  doc.text("Date", margin + 100, y + 13);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Complies with Australian Privacy Principle 3 (APP 3) - Collection of solicited personal information",
    margin,
    footerY
  );
  doc.text(
    `Generated by MySDAManager on ${new Date().toLocaleDateString("en-AU")}`,
    margin,
    footerY + 4
  );
  doc.text("Page 1 of 2", pageWidth - margin - 20, footerY + 4);

  // ── PAGE 2: PRIVACY INFORMATION SHEET ──────────────────────
  doc.addPage();

  // Header bar
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Privacy Information Sheet", margin, 20);

  y = 40;
  doc.setTextColor(0, 0, 0);

  // Section helper
  const addSection = (title: string, content: string) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(content, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 6;
  };

  addSection(
    "Your Privacy Rights",
    "Under the Australian Privacy Act 1988 and the NDIS Act 2013, you have the right to know what personal " +
      "information we collect, why we collect it, who we share it with, and how you can access or correct your information. " +
      "This sheet explains these rights in plain language."
  );

  addSection(
    "What We Collect and Why",
    "We collect your personal information (name, contact details, NDIS number, date of birth) and health information " +
      "(SDA needs, disability support requirements) to:\n" +
      "- Manage your SDA tenancy and accommodation agreement\n" +
      "- Process SDA funding claims with the NDIS\n" +
      "- Coordinate with your SIL provider and support coordinator\n" +
      "- Meet our regulatory and reporting obligations\n" +
      "- Ensure the safety and suitability of your accommodation"
  );

  addSection(
    "Who We Share Your Information With",
    "We may share your information with:\n" +
      "- The National Disability Insurance Agency (NDIA) for funding and compliance purposes\n" +
      "- Your nominated SIL provider for daily support coordination\n" +
      "- Your Support Coordinator or Plan Manager as required\n" +
      "- Occupational Therapists conducting SDA assessments\n" +
      "- Emergency services when required for your safety\n" +
      "- Government bodies where legally required\n\n" +
      "We will never sell your personal information or share it for marketing purposes."
  );

  addSection(
    "How We Store Your Information",
    "Your information is stored securely in our digital management system with encryption at rest. " +
      "Access is restricted to authorised staff only. We retain your information for 7 years after your " +
      "tenancy ends, as required by NDIS record-keeping obligations."
  );

  addSection(
    "How to Withdraw Consent",
    "You can withdraw your consent at any time by contacting your property manager or SDA provider in writing. " +
      "If you withdraw consent:\n" +
      "- We will stop collecting new personal information\n" +
      "- Your NDIS number, date of birth, and emergency contacts will be archived\n" +
      "- Records required for legal or compliance purposes will be retained\n" +
      "- This may affect our ability to manage your SDA tenancy and process NDIS claims"
  );

  addSection(
    "How to Access or Correct Your Information",
    "You have the right to request access to your personal information at any time. " +
      "If you believe any information is incorrect, you can request a correction. " +
      "Contact your SDA provider directly to make a request."
  );

  addSection(
    "Making a Complaint",
    "If you believe your privacy has been breached, you can:\n" +
      "1. Contact us directly to lodge a complaint\n" +
      "2. Contact the NDIS Quality and Safeguards Commission: 1800 035 544\n" +
      "3. Contact the Office of the Australian Information Commissioner (OAIC):\n" +
      "   Phone: 1300 363 992 | Website: www.oaic.gov.au"
  );

  // Footer
  const footer2Y = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `${orgName} | Generated by MySDAManager on ${new Date().toLocaleDateString("en-AU")}`,
    margin,
    footer2Y
  );
  doc.text("Page 2 of 2", pageWidth - margin - 20, footer2Y);

  // ── PAGES 3-4: EASY READ VERSION ──────────────────────────

  addEasyReadPages(doc, { orgName, participantName, pageWidth, margin, contentWidth });

  // Trigger download
  const safeName = participantName.replace(/[^a-zA-Z0-9]/g, "_");
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`Consent_Form_${safeName}_${dateStr}.pdf`);
}

/**
 * Generate a standalone Easy Read consent form PDF (12 pages).
 * Follows NDIS Quality and Safeguards Commission Easy Read format:
 * - Very large text (14-16pt body, 20-24pt headings)
 * - Maximum 2-3 concepts per page with generous white space
 * - One idea per sentence, one sentence per line
 * - Bold key terms defined in a word list at the end
 * - Cover page, "How to use this form" page, word list, contact page
 * - Active voice, second person ("you", "we")
 * - Complies with Australian Privacy Principle 3 (APP 3)
 */
export function generateEasyReadConsentPdf(params: ConsentFormParams): void {
  const { orgName, participantName } = params;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  // Total pages in the Easy Read document
  const TOTAL_PAGES = 12;

  // ── COLOUR PALETTE ──────────────────────────────────────

  const PURPLE = { r: 109, g: 40, b: 217 };
  const PURPLE_MID = { r: 139, g: 92, b: 246 }; // slightly lighter purple for accents
  const PURPLE_LIGHT = { r: 237, g: 233, b: 254 }; // lavender background
  const PURPLE_LIGHTER = { r: 245, g: 243, b: 255 }; // very subtle bg
  const WHITE = { r: 255, g: 255, b: 255 };
  const DARK = { r: 30, g: 30, b: 30 };

  // ── TWO-COLUMN LAYOUT CONSTANTS ─────────────────────────

  const illustColWidth = 68; // left column width for illustrations
  const gutter = 10; // gap between columns
  const rightColX = margin + illustColWidth + gutter; // right column starts here
  const rightColWidth = pageWidth - margin - rightColX; // right column text width
  const illustCenterX = margin + illustColWidth / 2; // center of illustration column

  // ── SHARED HELPERS ──────────────────────────────────────

  const addFooter = (pageNum: number) => {
    // Purple accent line
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.8);
    doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text("Easy Read Consent", margin, pageHeight - 12);
    doc.text(
      `Page ${pageNum} of ${TOTAL_PAGES}`,
      pageWidth - margin,
      pageHeight - 12,
      { align: "right" }
    );
  };

  const addPageHeader = (title: string) => {
    // Full-width purple header bar
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(0, 0, pageWidth, 30, "F");

    // Thin teal accent line below purple bar
    doc.setFillColor(13, 148, 136);
    doc.rect(0, 30, pageWidth, 2, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("EASY READ", margin, 10);
    doc.setFontSize(17);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, 24);
  };

  // Write body text in the right column at 14pt
  const writeBody = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, maxWidth ?? rightColWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBodyBold = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, maxWidth ?? rightColWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBullet = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(x + 2, y - 1.5, 1.8, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, (maxWidth ?? rightColWidth) - 10);
    doc.text(lines, x + 8, y);
    return y + lines.length * 7 + 2;
  };

  const writeSectionHeading = (text: string, x: number, y: number): number => {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text(text, x, y);
    return y + 10;
  };

  // Full-width body/bullet helpers for pages that need full width (signature, word list, contact)
  const writeBodyFull = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, maxWidth ?? contentWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBodyBoldFull = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, maxWidth ?? contentWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBulletFull = (text: string, x: number, y: number, maxWidth?: number): number => {
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(x + 2, y - 1.5, 1.8, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(DARK.r, DARK.g, DARK.b);
    const lines = doc.splitTextToSize(text, (maxWidth ?? contentWidth) - 10);
    doc.text(lines, x + 8, y);
    return y + lines.length * 7 + 2;
  };

  const writeSectionHeadingFull = (text: string, x: number, y: number): number => {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text(text, x, y);
    return y + 10;
  };

  // ── ILLUSTRATION DRAWING FUNCTIONS ──────────────────────
  // Each draws on a lavender background shape in the left column

  const drawBookIcon = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Left page of open book
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx - 20, cy - 14, 18, 24, "F");
    // Right page
    doc.rect(cx + 2, cy - 14, 18, 24, "F");

    // Spine line
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(1.2);
    doc.line(cx, cy - 16, cx, cy + 12);

    // Text lines on left page
    doc.setDrawColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.setLineWidth(0.6);
    doc.line(cx - 17, cy - 8, cx - 5, cy - 8);
    doc.line(cx - 17, cy - 3, cx - 7, cy - 3);
    doc.line(cx - 17, cy + 2, cx - 5, cy + 2);
    doc.line(cx - 17, cy + 7, cx - 9, cy + 7);

    // Text lines on right page
    doc.line(cx + 5, cy - 8, cx + 17, cy - 8);
    doc.line(cx + 5, cy - 3, cx + 15, cy - 3);
    doc.line(cx + 5, cy + 2, cx + 17, cy + 2);
    doc.line(cx + 5, cy + 7, cx + 13, cy + 7);
  };

  const drawPersonWithSpeechBubble = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 28, cy - 22, 56, 48, 6, 6, "F");

    // Head
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 8, cy - 10, 7, "F");

    // Body (trapezoid as triangle)
    doc.triangle(cx - 18, cy + 16, cx + 2, cy + 16, cx - 8, cy - 1, "F");

    // Speech bubble (rounded rect)
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx + 2, cy - 18, 24, 16, 3, 3, "F");
    // Bubble pointer triangle
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.triangle(cx + 5, cy - 2, cx + 12, cy - 2, cx + 6, cy + 3, "F");

    // Lines inside speech bubble
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.5);
    doc.line(cx + 6, cy - 13, cx + 22, cy - 13);
    doc.line(cx + 6, cy - 8, cx + 18, cy - 8);
  };

  const drawPersonWithDocument = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Person on the left
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 12, cy - 10, 6, "F"); // head
    doc.triangle(cx - 20, cy + 14, cx - 4, cy + 14, cx - 12, cy - 2, "F"); // body

    // Document on the right
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx + 4, cy - 14, 18, 24, "F");
    // Document border
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.6);
    doc.rect(cx + 4, cy - 14, 18, 24, "S");
    // Text lines on document
    doc.setLineWidth(0.4);
    doc.line(cx + 7, cy - 8, cx + 19, cy - 8);
    doc.line(cx + 7, cy - 3, cx + 17, cy - 3);
    doc.line(cx + 7, cy + 2, cx + 19, cy + 2);
    doc.line(cx + 7, cy + 7, cx + 15, cy + 7);
  };

  const drawHouseIcon = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 28, cy - 24, 56, 48, 6, 6, "F");

    // Roof (triangle)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.triangle(cx - 22, cy - 2, cx + 22, cy - 2, cx, cy - 20, "F");

    // Walls
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx - 16, cy - 2, 32, 22, "F");

    // Door
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 4, cy + 6, 8, 14, "F");
    // Door handle
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.circle(cx + 2, cy + 13, 1, "F");

    // Left window
    doc.setFillColor(200, 210, 255);
    doc.rect(cx - 13, cy + 2, 7, 7, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.4);
    doc.line(cx - 13, cy + 5.5, cx - 6, cy + 5.5);
    doc.line(cx - 9.5, cy + 2, cx - 9.5, cy + 9);

    // Right window
    doc.setFillColor(200, 210, 255);
    doc.rect(cx + 6, cy + 2, 7, 7, "F");
    doc.line(cx + 6, cy + 5.5, cx + 13, cy + 5.5);
    doc.line(cx + 9.5, cy + 2, cx + 9.5, cy + 9);
  };

  const drawClipboardChecklist = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Clipboard body
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx - 14, cy - 16, 28, 34, 2, 2, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.6);
    doc.roundedRect(cx - 14, cy - 16, 28, 34, 2, 2, "S");

    // Clip at top
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(cx - 6, cy - 20, 12, 8, 2, 2, "F");

    // Checklist items (3 rows)
    const checkY = [cy - 8, cy + 0, cy + 8];
    for (let i = 0; i < 3; i++) {
      // Checkbox
      doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
      doc.setLineWidth(0.5);
      doc.rect(cx - 10, checkY[i] - 2.5, 5, 5, "S");

      // Checkmark in first two boxes
      if (i < 2) {
        doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
        doc.setLineWidth(1);
        doc.line(cx - 9, checkY[i] + 0.5, cx - 7.5, checkY[i] + 2);
        doc.line(cx - 7.5, checkY[i] + 2, cx - 5.5, checkY[i] - 1.5);
      }

      // Text line
      doc.setDrawColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
      doc.setLineWidth(0.5);
      doc.line(cx - 2, checkY[i], cx + 10, checkY[i]);
    }
  };

  const drawIdCard = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 28, cy - 18, 56, 38, 6, 6, "F");

    // Card body
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx - 22, cy - 12, 44, 28, 3, 3, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.5);
    doc.roundedRect(cx - 22, cy - 12, 44, 28, 3, 3, "S");

    // Purple header bar on card
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 22, cy - 12, 44, 6, "F");

    // Photo placeholder (circle)
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx - 12, cy + 4, 6, "F");
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 12, cy + 2, 3, "F"); // head
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 12, cy + 9, 4, "F"); // shoulders hint

    // Text lines on card
    doc.setDrawColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.setLineWidth(0.5);
    doc.line(cx, cy, cx + 18, cy);
    doc.line(cx, cy + 5, cx + 14, cy + 5);
    doc.line(cx, cy + 10, cx + 18, cy + 10);
  };

  const drawGroupOfPeople = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Back person (lighter)
    doc.setFillColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.circle(cx, cy - 14, 6, "F"); // head
    doc.triangle(cx - 10, cy + 8, cx + 10, cy + 8, cx, cy - 6, "F"); // body

    // Left person
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 14, cy - 8, 5.5, "F"); // head
    doc.triangle(cx - 22, cy + 14, cx - 6, cy + 14, cx - 14, cy - 0.5, "F"); // body

    // Right person
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx + 14, cy - 8, 5.5, "F"); // head
    doc.triangle(cx + 6, cy + 14, cx + 22, cy + 14, cx + 14, cy - 0.5, "F"); // body
  };

  const drawHandshake = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 28, cy - 18, 56, 38, 6, 6, "F");

    // Left arm
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0);
    // Left forearm (angled rectangle via polygon shape using lines)
    doc.rect(cx - 24, cy - 3, 18, 6, "F");

    // Right arm (slightly lighter)
    doc.setFillColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.rect(cx + 6, cy - 3, 18, 6, "F");

    // Clasped hands in the middle (overlapping circles)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 2, cy, 5, "F");
    doc.setFillColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.circle(cx + 2, cy, 5, "F");

    // White hand lines (fingers suggestion)
    doc.setDrawColor(WHITE.r, WHITE.g, WHITE.b);
    doc.setLineWidth(0.6);
    doc.line(cx - 4, cy - 2, cx - 1, cy - 2);
    doc.line(cx + 1, cy + 2, cx + 4, cy + 2);

    // Heart above handshake
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 3, cy - 11, 3, "F");
    doc.circle(cx + 3, cy - 11, 3, "F");
    doc.triangle(cx - 6, cy - 10, cx + 6, cy - 10, cx, cy - 4, "F");
  };

  const drawShieldWithCheckmark = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Shield shape (composed of rect + triangle bottom)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 14, cy - 16, 28, 20, "F"); // upper rect
    doc.triangle(cx - 14, cy + 4, cx + 14, cy + 4, cx, cy + 18, "F"); // pointed bottom

    // Inner shield (white)
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx - 10, cy - 12, 20, 14, "F");
    doc.triangle(cx - 10, cy + 2, cx + 10, cy + 2, cx, cy + 12, "F");

    // Checkmark
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(2.5);
    doc.line(cx - 5, cy - 1, cx - 1, cy + 4);
    doc.line(cx - 1, cy + 4, cx + 7, cy - 6);
  };

  const drawRaisedHand = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 24, cy - 20, 48, 42, 6, 6, "F");

    // Palm base
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(cx - 10, cy - 4, 20, 18, 4, 4, "F");

    // Fingers (5 rounded rects)
    doc.roundedRect(cx - 10, cy - 16, 5, 16, 2, 2, "F"); // pinky
    doc.roundedRect(cx - 4, cy - 19, 5, 18, 2, 2, "F"); // ring
    doc.roundedRect(cx + 2, cy - 20, 5, 20, 2, 2, "F"); // middle
    doc.roundedRect(cx + 8, cy - 18, 5, 17, 2, 2, "F"); // index

    // Thumb
    doc.roundedRect(cx - 14, cy - 4, 6, 12, 2, 2, "F");

    // White "STOP" text or line across palm
    doc.setDrawColor(WHITE.r, WHITE.g, WHITE.b);
    doc.setLineWidth(0.8);
    doc.line(cx - 6, cy + 2, cx + 6, cy + 2);
    doc.line(cx - 6, cy + 5, cx + 6, cy + 5);
    doc.line(cx - 5, cy + 8, cx + 5, cy + 8);
  };

  const drawCalendar = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Calendar body
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx - 16, cy - 12, 32, 28, 2, 2, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.5);
    doc.roundedRect(cx - 16, cy - 12, 32, 28, 2, 2, "S");

    // Purple top bar (month header)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 16, cy - 12, 32, 8, "F");

    // Hanging loops
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(1.2);
    doc.line(cx - 8, cy - 15, cx - 8, cy - 10);
    doc.line(cx + 8, cy - 15, cx + 8, cy - 10);

    // Large "12" text
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text("12", cx, cy + 6, { align: "center" });

    // Small "months" text below
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text("months", cx, cy + 12, { align: "center" });
  };

  const drawClockFace = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 24, cy - 18, 48, 38, 6, 6, "F");

    // Clock circle
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.circle(cx, cy, 14, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(1.5);
    doc.circle(cx, cy, 14, "S");

    // Hour markers (12, 3, 6, 9)
    doc.setLineWidth(0.8);
    doc.line(cx, cy - 12, cx, cy - 10); // 12
    doc.line(cx + 12, cy, cx + 10, cy); // 3
    doc.line(cx, cy + 12, cx, cy + 10); // 6
    doc.line(cx - 12, cy, cx - 10, cy); // 9

    // Hour hand (pointing to 10)
    doc.setLineWidth(1.5);
    doc.line(cx, cy, cx - 5, cy - 7);

    // Minute hand (pointing to 2)
    doc.setLineWidth(1);
    doc.line(cx, cy, cx + 7, cy - 8);

    // Center dot
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx, cy, 1.5, "F");
  };

  const drawPadlock = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Lock shackle (arc at top)
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(3);
    // Draw arc as two vertical lines and a curve approximation
    doc.line(cx - 8, cy - 4, cx - 8, cy - 12);
    doc.line(cx + 8, cy - 4, cx + 8, cy - 12);
    // Top curve (approximated with small segments)
    doc.line(cx - 8, cy - 12, cx - 6, cy - 16);
    doc.line(cx - 6, cy - 16, cx - 2, cy - 18);
    doc.line(cx - 2, cy - 18, cx + 2, cy - 18);
    doc.line(cx + 2, cy - 18, cx + 6, cy - 16);
    doc.line(cx + 6, cy - 16, cx + 8, cy - 12);

    // Lock body
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(cx - 12, cy - 4, 24, 18, 2, 2, "F");

    // Keyhole
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.circle(cx, cy + 2, 3, "F");
    doc.rect(cx - 1.2, cy + 4, 2.4, 5, "F");
  };

  const drawComputerWithShield = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 26, cy - 18, 52, 40, 6, 6, "F");

    // Monitor
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx - 18, cy - 14, 36, 24, 2, 2, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(1);
    doc.roundedRect(cx - 18, cy - 14, 36, 24, 2, 2, "S");

    // Screen
    doc.setFillColor(PURPLE_LIGHTER.r, PURPLE_LIGHTER.g, PURPLE_LIGHTER.b);
    doc.rect(cx - 15, cy - 11, 30, 18, "F");

    // Monitor stand
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 3, cy + 10, 6, 4, "F");
    doc.rect(cx - 8, cy + 14, 16, 2, "F");

    // Small shield on screen
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 6, cy - 8, 12, 8, "F");
    doc.triangle(cx - 6, cy, cx + 6, cy, cx, cy + 6, "F");

    // White check on shield
    doc.setDrawColor(WHITE.r, WHITE.g, WHITE.b);
    doc.setLineWidth(1.5);
    doc.line(cx - 2, cy - 2, cx, cy + 1);
    doc.line(cx, cy + 1, cx + 3, cy - 4);
  };

  const drawPenOnPaper = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Paper
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx - 14, cy - 16, 22, 30, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.5);
    doc.rect(cx - 14, cy - 16, 22, 30, "S");

    // Lines on paper
    doc.setDrawColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.setLineWidth(0.4);
    doc.line(cx - 10, cy - 8, cx + 4, cy - 8);
    doc.line(cx - 10, cy - 3, cx + 2, cy - 3);
    doc.line(cx - 10, cy + 2, cx + 4, cy + 2);

    // Signature scribble line
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.8);
    doc.line(cx - 8, cy + 8, cx - 4, cy + 6);
    doc.line(cx - 4, cy + 6, cx, cy + 10);
    doc.line(cx, cy + 10, cx + 4, cy + 7);

    // Pen (diagonal)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    // Pen body (rotated appearance via lines)
    doc.setLineWidth(2.5);
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.line(cx + 6, cy - 4, cx + 18, cy - 16);
    // Pen tip
    doc.setLineWidth(1);
    doc.line(cx + 5, cy - 2, cx + 6, cy - 4);
    doc.line(cx + 7, cy - 3, cx + 6, cy - 4);
  };

  const drawTelephone = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Phone body (rounded rect)
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(cx - 10, cy - 18, 20, 36, 6, 6, "F");

    // Screen area
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx - 7, cy - 13, 14, 20, 2, 2, "F");

    // Home button
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.circle(cx, cy + 12, 2.5, "F");

    // Phone icon on screen
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    // Handset shape using circles and rect
    doc.circle(cx - 4, cy - 7, 2.5, "F");
    doc.circle(cx + 4, cy + 1, 2.5, "F");
    doc.setLineWidth(2);
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.line(cx - 3, cy - 5, cx + 3, cy - 1);
  };

  const drawPersonSpeaking = (cx: number, cy: number) => {
    // Lavender background rounded rect
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 26, cy - 18, 52, 40, 6, 6, "F");

    // Person
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(cx - 10, cy - 6, 7, "F"); // head
    doc.triangle(cx - 20, cy + 16, cx, cy + 16, cx - 10, cy + 3, "F"); // body

    // Speech bubble with exclamation
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(cx + 2, cy - 16, 22, 18, 4, 4, "F");
    doc.setDrawColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.setLineWidth(0.6);
    doc.roundedRect(cx + 2, cy - 16, 22, 18, 4, 4, "S");

    // Bubble pointer
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.triangle(cx + 5, cy + 2, cx + 12, cy + 2, cx + 4, cy + 7, "F");

    // Exclamation mark "!"
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text("!", cx + 13, cy - 2, { align: "center" });
  };

  const drawDictionaryBook = (cx: number, cy: number) => {
    // Lavender background circle
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.circle(cx, cy, 26, "F");

    // Book body
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(cx - 16, cy - 16, 32, 32, 2, 2, "F");

    // Book pages (white interior)
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(cx - 13, cy - 13, 26, 26, "F");

    // Spine
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 16, cy - 16, 4, 32, "F");

    // "A-Z" text on the cover
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text("A", cx - 1, cy - 2, { align: "center" });
    doc.setFontSize(8);
    doc.text("to", cx + 3, cy - 2);
    doc.setFontSize(14);
    doc.text("Z", cx + 6, cy + 6);

    // Lines representing definitions
    doc.setDrawColor(PURPLE_MID.r, PURPLE_MID.g, PURPLE_MID.b);
    doc.setLineWidth(0.4);
    doc.line(cx - 8, cy + 10, cx + 10, cy + 10);
  };

  const drawContactIcons = (cx: number, cy: number) => {
    // Lavender background rounded rect (wider for 3 icons)
    doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
    doc.roundedRect(cx - 30, cy - 20, 60, 42, 6, 6, "F");

    // === Phone icon (left) ===
    const px = cx - 18;
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(px - 5, py(cy, -12), 10, 18, 3, 3, "F");
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.roundedRect(px - 3, py(cy, -8), 6, 10, 1, 1, "F");

    // === Envelope icon (center) ===
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(cx - 10, cy - 6, 20, 14, "F");
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    // Envelope flap (triangle)
    doc.setDrawColor(WHITE.r, WHITE.g, WHITE.b);
    doc.setLineWidth(1);
    doc.line(cx - 10, cy - 6, cx, cy + 2);
    doc.line(cx + 10, cy - 6, cx, cy + 2);

    // === Computer icon (right) ===
    const rx = cx + 18;
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.roundedRect(rx - 8, cy - 10, 16, 12, 1, 1, "F");
    doc.setFillColor(WHITE.r, WHITE.g, WHITE.b);
    doc.rect(rx - 6, cy - 8, 12, 8, "F");
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(rx - 2, cy + 2, 4, 3, "F");
    doc.rect(rx - 5, cy + 5, 10, 2, "F");
  };

  // Helper for drawContactIcons to avoid nested function scope confusion
  function py(base: number, offset: number): number {
    return base + offset;
  }

  // ════════════════════════════════════════════════════════
  // PAGE 1: COVER PAGE
  // ════════════════════════════════════════════════════════

  // Full purple background
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Decorative circles (subtle lighter-purple on purple background, simulating 8% white opacity)
  doc.setFillColor(121, 57, 220); // purple blended with ~8% white
  doc.circle(pageWidth - 20, 30, 50, "F");
  doc.circle(30, pageHeight - 40, 60, "F");
  doc.circle(pageWidth - 60, pageHeight - 80, 30, "F");
  doc.circle(50, 60, 20, "F");

  // Teal accent bar at top
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 4, "F");

  // Easy Read badge (white pill shape)
  const badgeW = 90;
  const badgeH = 18;
  const badgeX = (pageWidth - badgeW) / 2;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(badgeX, 44, badgeW, badgeH, 9, 9, "F");
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.text("Easy Read", pageWidth / 2, 56, { align: "center" });

  // Main title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(
    "Saying Yes to Sharing Your Information",
    contentWidth - 10
  );
  doc.text(titleLines, pageWidth / 2, 95, { align: "center" });

  // White divider line (simulated 40% opacity: blended with purple)
  doc.setDrawColor(167, 126, 232); // purple blended with ~40% white
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 120, pageWidth / 2 + 40, 120);

  // Subtitle
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.text("A consent form about your", pageWidth / 2, 134, { align: "center" });
  doc.text("personal information", pageWidth / 2, 144, { align: "center" });

  // Decorative document icon in center (simulated 15% white on purple)
  doc.setFillColor(131, 72, 223); // purple blended with ~15% white
  doc.roundedRect(pageWidth / 2 - 18, 158, 36, 44, 3, 3, "F");
  // Checkmark on document (simulated 30% white on purple)
  doc.setDrawColor(153, 105, 228); // purple blended with ~30% white
  doc.setLineWidth(2);
  doc.line(pageWidth / 2 - 6, 178, pageWidth / 2 - 1, 184);
  doc.line(pageWidth / 2 - 1, 184, pageWidth / 2 + 8, 172);

  // Organisation name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(orgName, pageWidth / 2, 218, { align: "center" });

  // Participant name
  if (participantName) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`Prepared for: ${participantName}`, pageWidth / 2, 232, { align: "center" });
  }

  // Date
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(
    new Date().toLocaleDateString("en-AU", {
      year: "numeric",
      month: "long",
    }),
    pageWidth / 2,
    250,
    { align: "center" }
  );

  // Footer compliance note (simulated 70% white on purple = lighter text)
  doc.setFontSize(10);
  doc.setTextColor(211, 190, 244); // purple blended with ~70% white
  doc.text(
    "Complies with Australian Privacy Principle 3 (APP 3)",
    pageWidth / 2,
    pageHeight - 28,
    { align: "center" }
  );

  addFooter(1);

  // ════════════════════════════════════════════════════════
  // PAGE 2: HOW TO USE THIS FORM
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("How to Use This Form");

  let y = 42;

  // -- Illustration 1: Open Book --
  drawBookIcon(illustCenterX, y + 20);

  // Right column text
  let ry = y;
  ry = writeSectionHeading("This form is Easy Read", rightColX, ry);
  ry = writeBody("This form is written in Easy Read.", rightColX, ry);
  ry += 4;
  ry = writeBody("Easy Read uses simple words and short sentences.", rightColX, ry);
  ry += 4;
  ry = writeBody("Easy Read makes information easier to understand.", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: Person with Speech Bubble --
  drawPersonWithSpeechBubble(illustCenterX, y + 20);

  // Callout box for bold words explanation
  ry = y;
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(rightColX, ry - 2, rightColWidth, 34, 3, 3, "F");
  ry += 6;
  ry = writeBodyBold("Some words are written in bold.", rightColX + 4, ry, rightColWidth - 8);
  ry += 2;
  ry = writeBody("Bold means the text is thicker and darker.", rightColX + 4, ry, rightColWidth - 8);
  ry += 2;
  ry = writeBody("There is a word list at the end.", rightColX + 4, ry, rightColWidth - 8);

  y = Math.max(y + 52, ry) + 10;

  // -- Section: Ask for help (full width below illustrations) --
  y = writeSectionHeadingFull("You can ask for help", margin, y);
  y = writeBodyFull("You do not have to read this form by yourself.", margin, y);
  y += 4;
  y = writeBodyFull("You can ask someone you trust to help you.", margin, y);
  y += 4;
  y = writeBodyFull("This could be a family member, a friend, or a worker.", margin, y);
  y += 4;
  y = writeBodyBoldFull("An advocate is a person who speaks up for you.", margin, y);
  y += 8;

  y = writeSectionHeadingFull("Take your time", margin, y);
  y = writeBodyFull("You do not have to say yes straight away.", margin, y);
  y += 4;
  y = writeBodyFull("You can take this form home and think about it.", margin, y);
  y += 4;
  y = writeBodyFull("You can ask questions at any time.", margin, y);

  addFooter(2);

  // ════════════════════════════════════════════════════════
  // PAGE 3: WHAT THIS FORM IS ABOUT
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("What This Form Is About");

  y = 42;

  // -- Illustration 1: Person with Document --
  drawPersonWithDocument(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeSectionHeading("Your personal information", rightColX, ry);
  ry = writeBody("This form is about your personal information.", rightColX, ry);
  ry += 5;
  ry = writeBodyBold("Personal information is information about you.", rightColX, ry);
  ry += 3;
  ry = writeBody("Like your name, your birthday, and where you live.", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: House --
  drawHouseIcon(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeSectionHeading("We need some information", rightColX, ry);
  ry = writeBody("We need some of your information.", rightColX, ry);
  ry += 4;
  ry = writeBody("We use it to help you with your home.", rightColX, ry);

  y = Math.max(y + 52, ry) + 10;

  // -- Highlighted box: Your choice (full width) --
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 4, contentWidth, 52, 4, 4, "F");
  // Purple left accent bar on callout
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(margin, y - 4, 4, 52, "F");
  y += 4;

  y = writeSectionHeadingFull("It is your choice", margin + 10, y);
  y = writeBodyFull("You can say yes.", margin + 10, y, contentWidth - 16);
  y += 4;
  y = writeBodyFull("You can say no.", margin + 10, y, contentWidth - 16);
  y += 4;
  y = writeBodyFull("Nobody will be angry if you say no.", margin + 10, y, contentWidth - 16);

  y += 14;

  y = writeBodyFull("If you say no, we may not be able to do some things.", margin, y);
  y += 4;
  y = writeBodyFull("For example, we may not be able to claim your NDIS funding for your home.", margin, y);
  y += 5;
  y = writeBodyFull("We will explain this to you before you decide.", margin, y);

  addFooter(3);

  // ════════════════════════════════════════════════════════
  // PAGE 4: WHAT WE WILL COLLECT
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("What We Will Collect");

  y = 42;

  // -- Illustration 1: Clipboard Checklist --
  drawClipboardChecklist(illustCenterX, y + 22);

  // Right column text
  ry = y;
  ry = writeSectionHeading("We will collect:", rightColX, ry);
  ry = writeBullet("Your name", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your date of birth", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your address and phone number", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your NDIS number", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your health needs and disability information", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your emergency contact details", rightColX, ry);

  y = Math.max(y + 56, ry) + 10;

  // -- Illustration 2: ID Card --
  drawIdCard(illustCenterX, y + 16);

  // Right column text
  ry = y;
  ry = writeSectionHeading("Why we collect it:", rightColX, ry);
  ry = writeBullet("To help you live in your home", rightColX, ry);
  ry += 2;
  ry = writeBullet("To make sure your home is right for you", rightColX, ry);
  ry += 2;
  ry = writeBullet("To claim your NDIS funding", rightColX, ry);
  ry += 2;
  ry = writeBullet("To keep you safe", rightColX, ry);

  y = Math.max(y + 40, ry) + 8;

  // -- Full width note --
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 3, contentWidth, 14, 3, 3, "F");
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(margin, y - 3, 4, 14, "F");
  y += 5;
  y = writeBodyBoldFull("We only collect what we need.", margin + 10, y, contentWidth - 16);

  addFooter(4);

  // ════════════════════════════════════════════════════════
  // PAGE 5: WHO WE MAY SHARE WITH
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("Who We May Share With");

  y = 42;

  // -- Illustration 1: Group of People --
  drawGroupOfPeople(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeBody("Sometimes we need to share your information.", rightColX, ry);
  ry += 4;
  ry = writeBody("We only share what is needed.", rightColX, ry);
  ry += 4;
  ry = writeBodyBold("We will never sell your information.", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: Handshake --
  drawHandshake(illustCenterX, y + 16);

  // Right column: sharing list
  ry = y;
  ry = writeSectionHeading("We may share with:", rightColX, ry);
  ry = writeBullet("The NDIA -- they manage your NDIS funding", rightColX, ry);
  ry += 3;
  ry = writeBullet("Your SIL provider -- they help you day to day", rightColX, ry);
  ry += 3;
  ry = writeBullet("Your support coordinator -- they help you use your NDIS plan", rightColX, ry);
  ry += 3;
  ry = writeBullet("Doctors or therapists -- if needed for your health", rightColX, ry);
  ry += 3;
  ry = writeBullet("Emergency services -- if you are in danger", rightColX, ry);
  ry += 3;
  ry = writeBullet("Government -- only when the law says we must", rightColX, ry);

  y = Math.max(y + 44, ry) + 8;

  // Important callout box (full width)
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 3, contentWidth, 18, 3, 3, "F");
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(margin, y - 3, 4, 18, "F");
  y += 5;
  y = writeBodyBoldFull("We will never share your information for advertising or marketing.", margin + 10, y, contentWidth - 16);

  addFooter(5);

  // ════════════════════════════════════════════════════════
  // PAGE 6: YOUR RIGHTS
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("Your Rights");

  y = 42;

  // -- Illustration 1: Shield with Checkmark --
  drawShieldWithCheckmark(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeBody("You have rights about your information.", rightColX, ry);
  ry += 4;
  ry = writeBodyBold("Rights are things you are allowed to do.", rightColX, ry);
  ry += 4;
  ry = writeBody("The law gives you these rights.", rightColX, ry);

  y = Math.max(y + 52, ry) + 6;

  // -- Illustration 2: Raised Hand --
  drawRaisedHand(illustCenterX, y + 16);

  // Right column: rights list
  ry = y;
  ry = writeSectionHeading("You can see your information", rightColX, ry);
  ry = writeBody("You can ask us to show you the information we have about you.", rightColX, ry);
  ry += 3;
  ry = writeBody("We will show you for free.", rightColX, ry);

  y = Math.max(y + 44, ry) + 6;

  // Rights 2 & 3 full width
  y = writeSectionHeadingFull("You can fix your information", margin, y);
  y = writeBodyFull("If something is wrong, you can ask us to fix it.", margin, y);
  y += 3;
  y = writeBodyFull("For example, if we have the wrong phone number.", margin, y);
  y += 8;

  y = writeSectionHeadingFull("You can change your mind", margin, y);
  y = writeBodyFull("You can tell us to stop using your information.", margin, y);
  y += 3;
  y = writeBodyFull("This is called withdrawing your consent.", margin, y);
  y += 3;
  y = writeBodyFull("You can do this at any time.", margin, y);
  y += 3;
  y = writeBodyFull("Just tell us in person, by phone, or in writing.", margin, y);

  addFooter(6);

  // ════════════════════════════════════════════════════════
  // PAGE 7: HOW LONG THIS LASTS
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("How Long This Lasts");

  y = 42;

  // -- Illustration 1: Calendar --
  drawCalendar(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeSectionHeading("12 months", rightColX, ry);
  ry = writeBody("When you sign this form, it lasts for 12 months.", rightColX, ry);
  ry += 4;
  ry = writeBody("That means 1 year.", rightColX, ry);
  ry += 6;
  ry = writeSectionHeading("After 12 months", rightColX, ry);
  ry = writeBody("We will talk to you again.", rightColX, ry);
  ry += 3;
  ry = writeBody("We will ask if you still want to say yes.", rightColX, ry);
  ry += 3;
  ry = writeBody("You will get a new form to sign.", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: Clock Face --
  drawClockFace(illustCenterX, y + 16);

  // Right column text
  ry = y;
  ry = writeSectionHeading("You do not have to wait", rightColX, ry);
  ry = writeBody("You can change your mind before 12 months.", rightColX, ry);
  ry += 4;
  ry = writeBody("Just tell a staff member.", rightColX, ry);
  ry += 4;
  ry = writeBody("We will not be angry.", rightColX, ry);
  ry += 4;
  ry = writeBody("We will not treat you differently.", rightColX, ry);

  y = Math.max(y + 44, ry) + 8;

  // Callout box (full width)
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 3, contentWidth, 30, 3, 3, "F");
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(margin, y - 3, 4, 30, "F");
  y += 5;
  y = writeBodyBoldFull("If you change your mind:", margin + 10, y, contentWidth - 16);
  y += 2;
  y = writeBodyFull("We will stop collecting new information.", margin + 10, y, contentWidth - 16);
  y = writeBodyFull("We must keep some records the law says we need.", margin + 10, y, contentWidth - 16);

  addFooter(7);

  // ════════════════════════════════════════════════════════
  // PAGE 8: HOW WE KEEP YOUR INFORMATION SAFE
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("How We Keep Your Information Safe");

  y = 42;

  // -- Illustration 1: Padlock --
  drawPadlock(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeBody("We take good care of your information.", rightColX, ry);
  ry += 4;
  ry = writeBody("We keep it safe and private.", rightColX, ry);
  ry += 6;
  ry = writeSectionHeading("What we do:", rightColX, ry);
  ry = writeBullet("We store your information on secure computers", rightColX, ry);
  ry += 2;
  ry = writeBullet("Your information is locked with a password", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: Computer with Shield --
  drawComputerWithShield(illustCenterX, y + 16);

  // Right column text
  ry = y;
  ry = writeBullet("Only staff who need it can see your information", rightColX, ry);
  ry += 2;
  ry = writeBullet("We follow the Australian Privacy Principles", rightColX, ry);
  ry += 6;
  ry = writeSectionHeading("How long we keep it:", rightColX, ry);
  ry = writeBody("We keep your information for 7 years after you stop living in your home.", rightColX, ry);
  ry += 3;
  ry = writeBody("The law says we must do this.", rightColX, ry);
  ry += 3;
  ry = writeBody("After 7 years, we safely delete it.", rightColX, ry);

  y = Math.max(y + 44, ry);

  addFooter(8);

  // ════════════════════════════════════════════════════════
  // PAGE 9: SAYING YES (SIGNATURE PAGE)
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("Saying Yes");

  y = 42;

  // -- Illustration: Pen on Paper (in left column) --
  drawPenOnPaper(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeBody("If you want to say yes, you sign this page.", rightColX, ry);
  ry += 4;
  ry = writeBodyBold("Signing means you agree.", rightColX, ry);
  ry += 6;
  ry = writeSectionHeading("You are saying yes to:", rightColX, ry);
  ry = writeBullet("We can collect your personal information", rightColX, ry);
  ry += 2;
  ry = writeBullet("We can share it with the people on page 5", rightColX, ry);
  ry += 2;
  ry = writeBullet("You know your rights (page 6)", rightColX, ry);
  ry += 2;
  ry = writeBullet("This lasts for 12 months", rightColX, ry);
  ry += 2;
  ry = writeBullet("You can change your mind at any time", rightColX, ry);

  y = Math.max(y + 52, ry) + 10;

  // -- Signature area (full width) --
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 4, contentWidth, 78, 4, 4, "F");
  // Purple top accent bar
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.roundedRect(margin, y - 4, contentWidth, 6, 4, 4, "F");
  doc.rect(margin, y - 1, contentWidth, 3, "F"); // square off bottom corners of accent
  y += 8;

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(DARK.r, DARK.g, DARK.b);
  doc.setDrawColor(80, 80, 80);
  doc.setLineWidth(0.4);

  doc.text("Your name:", margin + 6, y);
  doc.line(margin + 40, y, margin + contentWidth - 8, y);
  y += 14;

  doc.text("Your signature:", margin + 6, y);
  doc.line(margin + 46, y, margin + contentWidth - 8, y);
  y += 14;

  doc.text("Today's date:", margin + 6, y);
  doc.line(margin + 42, y, margin + 90, y);
  y += 18;

  doc.text("Witness name:", margin + 6, y);
  doc.line(margin + 44, y, margin + contentWidth - 8, y);
  y += 14;

  doc.text("Witness signature:", margin + 6, y);
  doc.line(margin + 52, y, margin + 110, y);
  doc.text("Date:", margin + 116, y);
  doc.line(margin + 128, y, margin + contentWidth - 8, y);

  y += 16;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  const helpNote = doc.splitTextToSize(
    "You can bring a support person, family member, or advocate to help you understand this form before you sign.",
    contentWidth
  );
  doc.text(helpNote, margin, y);

  addFooter(9);

  // ════════════════════════════════════════════════════════
  // PAGE 10: IF YOU ARE UNHAPPY
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("If You Are Unhappy");

  y = 42;

  // -- Illustration 1: Telephone --
  drawTelephone(illustCenterX, y + 20);

  // Right column text
  ry = y;
  ry = writeBody("If you think we did something wrong with your information, you can make a complaint.", rightColX, ry);
  ry += 4;
  ry = writeBodyBold("A complaint is when you tell someone you are unhappy.", rightColX, ry);
  ry += 6;
  ry = writeSectionHeading("Step 1 -- Tell us first", rightColX, ry);
  ry = writeBody("Talk to a staff member at " + orgName + ".", rightColX, ry);
  ry += 3;
  ry = writeBody("We will try to fix the problem.", rightColX, ry);

  y = Math.max(y + 52, ry) + 8;

  // -- Illustration 2: Person Speaking --
  drawPersonSpeaking(illustCenterX, y + 16);

  // Right column text
  ry = y;
  ry = writeSectionHeading("Step 2 -- NDIS Commission", rightColX, ry);
  ry = writeBody("If we cannot fix it, you can call the NDIS Quality and Safeguards Commission.", rightColX, ry);
  ry += 3;

  // Phone number callout
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(rightColX, ry - 2, rightColWidth, 12, 3, 3, "F");
  ry += 6;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.text("Phone: 1800 035 544 (free call)", rightColX + 4, ry);
  ry += 8;

  y = Math.max(y + 44, ry) + 6;

  // Step 3 (full width)
  y = writeSectionHeadingFull("Step 3 -- Privacy Commissioner", margin, y);
  y = writeBodyFull("You can also contact the Office of the Australian Information Commissioner (OAIC).", margin, y);
  y += 3;

  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 2, contentWidth, 20, 3, 3, "F");
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(margin, y - 2, 4, 20, "F");
  y += 6;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.text("Phone: 1300 363 992", margin + 10, y);
  y += 8;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Website: www.oaic.gov.au", margin + 10, y);

  y += 12;
  y = writeBodyFull("A friend, family member, or advocate can help you make a complaint.", margin, y);

  addFooter(10);

  // ════════════════════════════════════════════════════════
  // PAGE 11: WORD LIST
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("Word List");

  y = 42;

  // -- Illustration: Dictionary Book --
  drawDictionaryBook(illustCenterX, y + 20);

  // Right column intro text
  ry = y;
  ry = writeBody("This is a list of words used in this form.", rightColX, ry);
  ry += 4;
  ry = writeBody("It tells you what they mean.", rightColX, ry);

  y = Math.max(y + 52, ry) + 6;

  // Word list (full width, two visual columns for terms)
  const wordList: Array<{ term: string; definition: string }> = [
    {
      term: "Advocate",
      definition: "A person who speaks up for you and helps you say what you want.",
    },
    {
      term: "Complaint",
      definition: "When you tell someone you are unhappy about something they did.",
    },
    {
      term: "Consent",
      definition: "When you say yes to something. You choose freely.",
    },
    {
      term: "Emergency contact",
      definition: "A person we call if something happens to you. Like a family member.",
    },
    {
      term: "NDIA",
      definition: "The National Disability Insurance Agency. They manage your NDIS plan.",
    },
    {
      term: "NDIS funding",
      definition: "Money from the NDIS that pays for your home and supports.",
    },
    {
      term: "OAIC",
      definition: "Office of the Australian Information Commissioner. They make sure organisations follow privacy rules.",
    },
    {
      term: "Personal information",
      definition: "Information about you. Like your name, birthday, and where you live.",
    },
    {
      term: "Privacy",
      definition: "Keeping your information safe and only sharing it when needed.",
    },
    {
      term: "Rights",
      definition: "Things you are allowed to do. The law gives you these rights.",
    },
    {
      term: "SIL provider",
      definition: "Supported Independent Living provider. They help you with daily things in your home.",
    },
    {
      term: "Support coordinator",
      definition: "A person who helps you use your NDIS plan and find services.",
    },
    {
      term: "Withdraw",
      definition: "To take back your consent. It means you change your mind and say no.",
    },
  ];

  for (let wi = 0; wi < wordList.length; wi++) {
    const item = wordList[wi];
    // Alternating subtle background for readability
    if (wi % 2 === 0) {
      doc.setFillColor(PURPLE_LIGHTER.r, PURPLE_LIGHTER.g, PURPLE_LIGHTER.b);
      doc.rect(margin, y - 3.5, contentWidth, 12, "F");
    }

    // Term in bold purple + definition inline
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text(item.term, margin + 2, y);

    // Definition on next line, compact
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(item.definition, margin + 4, y + 4.5);
    y += 12;
  }

  addFooter(11);

  // ════════════════════════════════════════════════════════
  // PAGE 12: CONTACT US
  // ════════════════════════════════════════════════════════

  doc.addPage();
  addPageHeader("Contact Us");

  y = 42;

  // -- Illustration: Contact Icons (Phone + Envelope + Computer) --
  drawContactIcons(illustCenterX, y + 18);

  // Right column text
  ry = y;
  ry = writeBody("If you have any questions about this form, please contact us.", rightColX, ry);

  y = Math.max(y + 48, ry) + 8;

  // Organisation details box (full width)
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 4, contentWidth, 56, 4, 4, "F");
  // Purple top accent
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.roundedRect(margin, y - 4, contentWidth, 6, 4, 4, "F");
  doc.rect(margin, y - 1, contentWidth, 3, "F");
  y += 10;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.text(orgName, margin + 6, y);
  y += 12;

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  doc.text("Phone: ____________________________", margin + 6, y);
  y += 10;

  doc.text("Email: ____________________________", margin + 6, y);
  y += 10;

  doc.text("Address: ____________________________", margin + 6, y);

  y += 20;

  y = writeSectionHeadingFull("Other places you can contact", margin, y);

  // NDIS Commission
  y = writeBodyBoldFull("NDIS Quality and Safeguards Commission", margin, y);
  y += 2;
  y = writeBodyFull("Phone: 1800 035 544 (free call)", margin, y);
  y += 2;
  y = writeBodyFull("Website: www.ndiscommission.gov.au", margin, y);
  y += 8;

  // OAIC
  y = writeBodyBoldFull("Office of the Australian Information Commissioner", margin, y);
  y += 2;
  y = writeBodyFull("Phone: 1300 363 992", margin, y);
  y += 2;
  y = writeBodyFull("Website: www.oaic.gov.au", margin, y);
  y += 8;

  // National Disability Advocacy
  y = writeBodyBoldFull("National Disability Advocacy Program", margin, y);
  y += 2;
  y = writeBodyFull("If you need an advocate, ask your support coordinator or call the Disability Advocacy Finder:", margin, y);
  y += 2;
  y = writeBodyFull("Website: disabilityadvocacyfinder.dss.gov.au", margin, y);

  addFooter(12);

  // ── SAVE ────────────────────────────────────────────────

  const safeName = participantName.replace(/[^a-zA-Z0-9]/g, "_");
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`Consent_Form_Easy_Read_${safeName}_${dateStr}.pdf`);
}

// ── Shared Easy Read page builder (appended to standard consent) ──

function addEasyReadPages(
  doc: jsPDF,
  opts: {
    orgName: string;
    participantName: string;
    pageWidth: number;
    margin: number;
    contentWidth: number;
    startPage?: number;
  }
): void {
  const { orgName, participantName, pageWidth, margin, contentWidth } = opts;
  const pageHeight = doc.internal.pageSize.getHeight();

  // When appended to the standard 2-page consent form, the Easy Read
  // section starts at page 3 as a condensed 4-page summary.
  // The standalone version (generateEasyReadConsentPdf) has the full 12-page format.

  const PURPLE = { r: 109, g: 40, b: 217 };
  const PURPLE_LIGHT = { r: 237, g: 233, b: 254 };

  // Determine page numbering based on context
  const basePageOffset = opts.startPage ? opts.startPage - 1 : 2;
  const appendedTotalPages = opts.startPage ? 4 : 6; // 4 standalone or 2 standard + 4 easy read

  const addFooter = (pageNum: number) => {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(140, 140, 140);
    doc.text("Easy Read", margin, pageHeight - 14);
    doc.text(
      `Page ${pageNum} of ${appendedTotalPages}`,
      pageWidth - margin - 24,
      pageHeight - 14
    );
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);
  };

  const addPageHeader = (title: string) => {
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.rect(0, 0, pageWidth, 28, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("EASY READ", margin, 10);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, 22);
  };

  const writeBody14 = (text: string, x: number, y: number, mw?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(text, mw ?? contentWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBodyBold14 = (text: string, x: number, y: number, mw?: number): number => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(text, mw ?? contentWidth);
    doc.text(lines, x, y);
    return y + lines.length * 7;
  };

  const writeBullet14 = (text: string, x: number, y: number, mw?: number): number => {
    doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.circle(x + 2, y - 1.5, 1.8, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(text, (mw ?? contentWidth) - 10);
    doc.text(lines, x + 8, y);
    return y + lines.length * 7 + 2;
  };

  const writeHeading18 = (text: string, x: number, y: number): number => {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text(text, x, y);
    return y + 12;
  };

  // ── APPENDED PAGE 1: COVER + ABOUT ──────────────────────

  const isStandalone = opts.startPage === 1;
  if (!isStandalone) {
    doc.addPage();
  }

  // Cover section
  doc.setFillColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.rect(0, 0, pageWidth, 60, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("EASY READ", margin, 10);
  doc.text(orgName, margin, 17);

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Saying Yes to Sharing", margin, 34);
  doc.text("Your Information", margin, 46);

  // Badge
  const bW = 50;
  const bX = pageWidth - margin - bW;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(bX, 22, bW, 12, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
  doc.text("Easy Read", bX + bW / 2, 30, { align: "center" });

  let y = 72;

  y = writeBody14("This form is about your personal information.", margin, y);
  y += 5;

  y = writeBodyBold14("Personal information is information about you.", margin, y);
  y += 3;

  y = writeBody14("Like your name, your birthday, and where you live.", margin, y);
  y += 8;

  y = writeBody14("We need some of your information.", margin, y);
  y += 3;

  y = writeBody14("We use it to help you with your home.", margin, y);
  y += 8;

  // Choice box
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 4, contentWidth, 26, 3, 3, "F");
  y += 4;

  y = writeHeading18("It is your choice", margin + 6, y);

  y = writeBody14("You can say yes or no.", margin + 6, y, contentWidth - 12);
  y += 3;

  y = writeBody14("Nobody will be angry if you say no.", margin + 6, y, contentWidth - 12);

  y += 16;

  y = writeBody14("You can ask someone to help you read this form.", margin, y);
  y += 3;

  y = writeBody14("Take your time. You can ask questions.", margin, y);
  y += 3;

  y = writeBodyBold14("Bold words are explained at the end.", margin, y);

  addFooter(basePageOffset + 1);

  // ── APPENDED PAGE 2: COLLECT + SHARE ──────────────────────

  doc.addPage();
  addPageHeader("What We Collect and Share");

  y = 40;

  y = writeHeading18("We will collect:", margin, y);

  y = writeBullet14("Your name, birthday, and phone number", margin, y);
  y += 2;

  y = writeBullet14("Your NDIS number", margin, y);
  y += 2;

  y = writeBullet14("Your health needs", margin, y);
  y += 2;

  y = writeBullet14("Your emergency contact", margin, y);
  y += 8;

  y = writeBody14("We only collect what we need to help you.", margin, y);
  y += 12;

  y = writeHeading18("We may share with:", margin, y);

  y = writeBullet14("The NDIA -- they manage your NDIS funding", margin, y);
  y += 2;

  y = writeBullet14("Your SIL provider -- they help you each day", margin, y);
  y += 2;

  y = writeBullet14("Your support coordinator", margin, y);
  y += 2;

  y = writeBullet14("Doctors or therapists if needed", margin, y);
  y += 2;

  y = writeBullet14("Emergency services if you are in danger", margin, y);
  y += 8;

  y = writeBodyBold14("We will never sell your information.", margin, y);
  y += 3;

  y = writeBody14("We only share what is needed.", margin, y);

  addFooter(basePageOffset + 2);

  // ── APPENDED PAGE 3: RIGHTS + SAFETY ──────────────────────

  doc.addPage();
  addPageHeader("Your Rights and Safety");

  y = 40;

  y = writeHeading18("Your rights", margin, y);

  y = writeBullet14("You can see the information we have about you", margin, y);
  y += 2;

  y = writeBullet14("You can ask us to fix anything that is wrong", margin, y);
  y += 2;

  y = writeBullet14("You can change your mind at any time", margin, y);
  y += 2;

  y = writeBullet14("This form lasts for 12 months (1 year)", margin, y);
  y += 2;

  y = writeBullet14("After 12 months, we will ask you again", margin, y);
  y += 10;

  y = writeHeading18("How we keep your information safe", margin, y);

  y = writeBullet14("We store it on secure computers", margin, y);
  y += 2;

  y = writeBullet14("Only the right staff can see it", margin, y);
  y += 2;

  y = writeBullet14("We follow the Australian Privacy Principles", margin, y);
  y += 2;

  y = writeBullet14("We keep records for 7 years as the law requires", margin, y);
  y += 10;

  y = writeHeading18("If you are unhappy", margin, y);

  y = writeBody14("Tell us first. We will try to fix it.", margin, y);
  y += 5;

  y = writeBody14("You can also call:", margin, y);
  y += 3;

  y = writeBullet14("NDIS Commission: 1800 035 544 (free)", margin, y);
  y += 2;

  y = writeBullet14("OAIC: 1300 363 992", margin, y);

  addFooter(basePageOffset + 3);

  // ── APPENDED PAGE 4: SIGN + WORD LIST ──────────────────────

  doc.addPage();
  addPageHeader("Saying Yes");

  y = 40;

  y = writeBody14("If you agree, sign below.", margin, y);
  y += 3;

  y = writeBody14("You can bring someone to help you.", margin, y);
  y += 8;

  // Signature box
  doc.setFillColor(PURPLE_LIGHT.r, PURPLE_LIGHT.g, PURPLE_LIGHT.b);
  doc.roundedRect(margin, y - 4, contentWidth, 56, 3, 3, "F");
  y += 6;

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.setDrawColor(80, 80, 80);
  doc.setLineWidth(0.4);

  doc.text("Name:", margin + 6, y);
  doc.line(margin + 28, y, margin + contentWidth - 8, y);
  y += 12;

  doc.text("Signature:", margin + 6, y);
  doc.line(margin + 36, y, margin + 100, y);
  doc.text("Date:", margin + 106, y);
  doc.line(margin + 122, y, margin + contentWidth - 8, y);
  y += 12;

  doc.text("Witness:", margin + 6, y);
  doc.line(margin + 32, y, margin + 100, y);
  doc.text("Date:", margin + 106, y);
  doc.line(margin + 122, y, margin + contentWidth - 8, y);

  y += 20;

  // Compact word list
  y = writeHeading18("Word List", margin, y);

  const compactWordList = [
    { term: "Advocate", def: "A person who speaks up for you." },
    { term: "Consent", def: "When you say yes. You choose freely." },
    { term: "NDIA", def: "They manage your NDIS plan and funding." },
    { term: "OAIC", def: "They make sure organisations follow privacy rules." },
    { term: "Personal information", def: "Information about you (name, birthday, etc.)." },
    { term: "Privacy", def: "Keeping your information safe and private." },
    { term: "Rights", def: "Things you are allowed to do." },
    { term: "SIL provider", def: "They help you with daily things in your home." },
    { term: "Support coordinator", def: "They help you use your NDIS plan." },
    { term: "Withdraw", def: "To change your mind and say no." },
  ];

  for (const item of compactWordList) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(PURPLE.r, PURPLE.g, PURPLE.b);
    doc.text(item.term, margin, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const termW = doc.getTextWidth(item.term);
    doc.text(" -- " + item.def, margin + termW, y);
    y += 6;
  }

  y += 6;

  // Contact footer
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`Contact ${orgName} if you have questions.`, margin, y);

  addFooter(basePageOffset + 4);
}
